### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by chamberm** [scilus/dmri-explorer#41]
As discussed in person, a Windows version would be great as well (both for users and devs). This requires Unix's pthread library to be either adapted or replaced.

**Comment by CHrlS98** [comment]
Hi,
I opened a PR (#42) which is a work in progress to try to get the code to compile under Windows. The `pthread` library does not seem to be a problem after all. It's `zlib`, the library used by `nifti_clib` to read compressed nifti images, that seems to have been the culprit. It now compiles, but it crashes at runtime. It still appears to be linked to `zlib`; I'll further investigate. We can move the discussion to the PR.
