### ISSUE TITLE
Flipped fODFs when stride is negative

### ISSUE THREAD

**Issue by karanphil** [scilus/dmri-explorer#43]
When loading fODF data with negative strides, the fODF appear flipped. For the moment I can flip the stride manually, but it would be nice to have it fixed at some point. Here is some flipped data for testing.

https://usherbrooke-my.sharepoint.com/:u:/g/personal/karp2601_usherbrooke_ca/EbdDFN4XWbZOlxMOTlHBK6gBS60dwKg2YC6IU0zaN4ju2Q?e=qRrVVI

**Comment by CHrlS98** [comment]
Can't reproduce on my machine with the data supplied for testing. Could you paste your system specifications? OpenGL version and graphics card more importantly. Thanks in advance.

**Comment by karanphil** [comment]
It appears to have nothing to do with the strides, since I get the flip either way. Might be linked to my old GTX 660. My OpenGL version is 4.6.0.
