### ISSUE TITLE
Unable to run on Windows 11 without NVidia GPU

### ISSUE THREAD

**Issue by neurolabusc** [scilus/dmri-explorer#52]
I believe this is related to [Pull Request 42](https://github.com/scilus/dmri-explorer/pull/42). The software compiles on my Windows 11 system. However, when I attempt to run the executable using the integrated graphics of my [i5-1240P](https://www.intel.com/content/www/us/en/products/sku/132221/intel-core-i51240p-processor-12m-cache-up-to-4-40-ghz/specifications.html) CPU that supports OpenGL 4.6.0 using the Intel drive 31.0.101.3790 I get the error `Required OpenGL ARB extension not available on system.` Perhaps the README.md should be updated as it seems like an NVidia GPU is a requirement for Windows usage.

**Comment by CHrlS98** [comment]
Hi @neurolabusc ,
Thanks for the issue. You are right, as of now the application has only ever been tested on nvidia hardware and does not run on integrated graphics card. It remains to be seen whether it would work if we worked our way around the requirement for OpenGL ARB extensions (and also how well it would run). As far as I know, it hasn't been tested on AMD dedicated graphics card either.

I'll just edit the documentation for now, but I'll investigate further in the future. Also, shouldn't the title for the issue read "Unable to run on Windows 11 **without** NVidia GPU"?

**Comment by neurolabusc** [comment]
@CHrlS98 I have changed the title. The performance of integrated graphics is getting progressively better. The performance of this computer is sufficient for tools like [NiiVue](https://niivue.github.io/niivue/features/tracts.html) or Surfice.
