### ISSUE TITLE
Add tensor support

### ISSUE THREAD

**Issue by GuillaumeTh** [scilus/dmri-explorer#7]
For figure purpose it could be cool to support tensors.

**Comment by CHrlS98** [comment]
@erickhernandezgutierrez If I'm not mistaken this will be done in your multi-tensor PR?

**Comment by ErickHernandezGutierrez** [comment]
Hi @CHrlS98  and @GuillaumeTh. Sorry for the late reply. Yes, it will. The multi-tensor feature supports single tensor visualization too. PR should be ready for tomorrow.
